# Generated by Django 5.1.3 on 2024-12-23 14:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal ID', unique=True, verbose_name='Internal ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the object is active or not', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the object was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the object was last updated', verbose_name='Updated At')),
                ('name', models.CharField(help_text='Country name', max_length=255, verbose_name='Country Name')),
                ('numeric_code', models.CharField(help_text='Country numeric code', max_length=10, verbose_name='Country Numeric Code')),
                ('alpha2_code', models.CharField(help_text='country alpha2 code', max_length=2, verbose_name='Country Alpha2 Code')),
                ('alpha3_code', models.CharField(help_text='Country alpha3 code', max_length=3, verbose_name='Country Alpha3 Code')),
                ('isd_code', models.CharField(help_text='Country alpha3 code', max_length=4, verbose_name='Country ISD Code')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal ID', unique=True, verbose_name='Internal ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the object is active or not', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the object was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the object was last updated', verbose_name='Updated At')),
                ('name', models.CharField(help_text='State name', max_length=255, verbose_name='State Name')),
                ('code', models.CharField(help_text='State code', max_length=5, verbose_name='State Code')),
                ('country', models.ForeignKey(help_text='Country', on_delete=django.db.models.deletion.CASCADE, related_name='states', to='base.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'states',
            },
        ),
    ]
